import { Title } from '@angular/platform-browser';

export interface CheckList1 {
    Id?: number,
    usuario_id?:number,
    Fecha?: Date,
    Vehiculo?: string,
    Realizado_por?: string,
    L_alta_baja?: string,
    L_intermitentes?: string,
    L_Marcha_atras?: string,
    L_freno?: string,
    Che_general_motor?: string,
    Sistema_pedal_freno?: string,
    Sistema_direccion?: string,
    N_combustible?: string,
    N_aceite?: string,
    N_liquido_frenos?: string,
    N_liquido_hidraulico?: string,
    N_dispositivo_agua?: string,
    Latoneria_pintura?: string,
    Equipo_refrijeracion?: string,
    bocina?: string,
    Cinturon_seguridad?: string,
    Tablero_control?: string,
    Espejos_retrovisores?: string,
    Estado_puertas?: string,
    Orden_aseo?: string,
    Soat_tarjeta?: string,
    Ll_delanteras?: string,
    Ll_traseras?: string,
    Ll_repuesto?: string,
    Aprete_ruedas?: string,
    K_botiquin?: string,
    K_extintor?: string,
    K_herramientas?: string,
    Otro?: string
};
